name: bloodline_sg
description: "🩸 Bloodline SG - A peer-led blood donation app for Singapore youths"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  
  # Routing
  go_router: ^16.2.0
  
  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_dynamic_links: ^6.0.4
  firebase_analytics: ^11.2.1
  
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Networking
  http: ^1.2.2
  html: ^0.15.4
  
  # Calendar & Notifications
  add_2_calendar: ^3.0.1
  # flutter_local_notifications: ^17.2.4  # Temporarily disabled due to desugaring requirement
  
  # Sharing & Utils
  share_plus: ^11.1.0
  uuid: ^4.4.2
  url_launcher: ^6.3.1
  
  # Location & Maps
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI & Design System
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  
  # Time zones (disabled with notifications)
  # timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  
  # Linting
  flutter_lints: ^6.0.0

  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/centres/
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dexterdonatingblood.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/dexterdonatingblood.png"
    background_color: "#4CAF50"
    theme_color: "#4CAF50"
  windows:
    generate: true
    image_path: "assets/images/dexterdonatingblood.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/dexterdonatingblood.png"